#!/usr/bin/python
import sys
import socket
import re
import select

#try input
args = str(sys.argv[1]).split(':')
ip = str(args[0])
port = int(args[1])
nick = str(sys.argv[2])
# Try protocol part 1 and protocol part 2
client = socket.socket()
if len(sys.argv) != 3:
    print("Usage: ./chatclient <server-ip>:<port-number> <nickname>")
    sys.exit(1)
    # connect to server

client.connect((ip, port))
hello = client.recv(1024).decode('ascii')
print(hello)
    # Send nick and receive ok
client.sendall(('NICK '+ nick).encode('ascii'))
ok = client.recv(1024).decode('ascii')
if re.search('Error',ok) or re.search('ERROR', ok):
    print(ok)
    sys.exit()
print(ok)
while True:
    sockets = [sys.stdin, client]
    read_sockets, write_sockets, error_sockets = select.select(sockets, [], [])
    for socket in read_sockets:
        if socket == client:
            msg = socket.recv(2048).decode('ascii')
            if re.search(r'Error', msg) or re.search(r'ERROR', msg):
                print(msg)
            else:
                print(msg[4:])  # error message
        else:
            msg = sys.stdin.readline()
            if msg == '\n':
                continue
            else:
                message_load = 'MSG ' + msg
                client.sendall(message_load.encode('ascii'))
client.close()
